# Generated by Django 6.0.1 on 2026-01-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_message', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
