# Generated by Django 6.0.1 on 2026-01-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serviece_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_price', models.IntegerField(blank=True, null=True)),
                ('service_description', models.TextField(blank=True, max_length=400, null=True)),
                ('service_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
