# Generated by Django 6.0.1 on 2026-01-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviece_db',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='serviece_images'),
        ),
    ]
