# Generated by Django 6.0.1 on 2026-01-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0002_serviece_db_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviece_db',
            name='service_short_desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
