# Generated by Django 6.0.1 on 2026-01-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0004_order_db'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_DB',
        ),
    ]
