# Generated by Django 6.0.1 on 2026-01-19 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0005_delete_order_db'),
        ('User_Web', '0002_contact_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('pickup_address', models.TextField(blank=True, max_length=300, null=True)),
                ('delivery_address', models.TextField(blank=True, max_length=300, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin_Panel.serviece_db')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Web.userregistration_db')),
            ],
        ),
    ]
