# Generated by Django 6.0.1 on 2026-01-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0006_order_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
