# Generated by Django 6.0.1 on 2026-01-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0008_order_db_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_db',
            name='status',
        ),
    ]
