# Generated by Django 6.0.1 on 2026-01-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0009_remove_order_db_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
